version: "3"
services:
  worker:
    image: stats-worker
    build:
        context: ..
        dockerfile: Stats.Worker/Dockerfile
    environment:
      STATS_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      
networks:
  default:
    external:
      name: shared-network    